package hu.gyuuu.hrmanager.security.enums;

public enum Authority
{
	APPROVE_USER, VIEW_SELF, VIEW_USERS, VIEW_COMPANIES, VIEW_WORKERS, MANAGE_OWN_WORKER, MANAGE_ANY_WORKER, RESERVE_WORKER, DECIDE_OWN_WORKER_RESERVATION
}
